import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "./Provider";
import { Toaster } from 'sonner';
import Footer from "@/components/layout/Footer";
import Nav from "@/components/layout/Nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Algorithmic Odyssey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative h-full font-sans`}>
        <main className="relative flex flex-col min-h-screen bg-[#eff1f5] dark:bg-[#1b1b1f]">
          <Provider>
            <Nav />
            <div className="relative h-full w-full">
              {children}
              <Toaster position="bottom-right" richColors/>
            </div>
            <Footer />

          </Provider>
        </main>
      </body>
    </html>
  );
}
