import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Provider} from "./Provider";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Algorithmic Odyssey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body className={`${inter.className} relative h-full font-sans`}>
<main className="relative flex flex-col min-h-screen"> 
     <Provider>
     <NavBar />
       <div className="relative h-full w-full ">
    {children}
       </div>
        </Provider>
        <Footer />
        </main>
        </body>
    </html>
  );
}
